# Generated by Django 5.1.1 on 2024-09-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_firtname_login_lastname_login_numberphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='numberPhone',
            field=models.CharField(default='SinNombre', max_length=10),
        ),
    ]
