# Generated by Django 5.1.1 on 2024-09-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_login_numberphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='firtName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='login',
            name='lastName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='login',
            name='numberPhone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='login',
            name='userName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
